Sprint_2
KrylovaLena/qa_python pull request #2
Opened 2023-12-13 14:40 UTC by KrylovaLena

2023-12-14 18:33 UTC, kadirovgm requested changes

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +    # Тестирование добавления новой книги с разными валидными названиями
Можно лучше: это хорошо, что ты коротко описываешь, что делает каждая тестовая функция, но я бы предложил это делать в виде коммента в формате "докстринг", и убрать слово "тестирование", потому что это и так понятно, что функции тестовые :)

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        assert name in collector.books_genre
нужно исправить: для вывода словаря books_genre есть метод get_books_genre() - так что давай использовать его

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        assert book_name in collector.books_genre and len(collector.get_books_genre()) == 1
нужно исправить: get_books_genre() и тут кстати наверное уже хватит только проверки len(collector.get_books_genre()) == 1

потому что проверку добавления книги в словарь ты уже делал тестом выше

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +    def test_add_new_book_long_book_title(self):
нужно исправить: давай напишем параметризированный тест, который будет проверять все граничные значения входных данных

параметризация - это когда на вход теста передают тестовые данные из разных классов эквивалентности, при этом зная, что тест вернет одно и то же значение

тест1: передаем книги с длиной названия 0, 41, 42 - книги в словарь не добавлены
тест2: передаем книги с длиной названия 1, 2, 39, 40 - книги в словарь добавлены

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        book_name = "Сказка о Тройке. История непримиримой борьбы за повышение трудовой дисциплины, против бюрократизма, за высокий моральный уровень, против обезлички, за здоровую критику и здоровую
Можно лучше: не обязательно писать такой огромный тайтл, ведь достаточно проверить на количестве букв = 41 :)

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        assert book_name not in collector.books_genre and len(collector.get_books_genre()) == 0
нужно исправить: достаточно len(collector.get_books_genre()) == 0

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        assert collector.books_genre["Властелин Колец"] == "Фантастика"
нужно исправить: метод get_book_genre(book)

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        assert collector.books_genre.get("Властелин Колец") == ''
нужно исправить: метод get_book_genre(book)

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        assert "Властелин Колец" not in collector.books_genre
нужно исправить: метод get_books_genre

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('genre', ['Ужасы', 'Детективы'])
нужно исправить: для чего тут параметризация ? если ты эти параметры не применяешь

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        assert book_name in collector.favorites
нужно исправить: для этого есть метод get_list_of_favorite_books()

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        collector.favorites.append(book_name)
нужно исправить: зачем? ведь есть метод add_book_in_favorites

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        assert book_name not in collector.favorites
нужно исправить: для этого есть метод get_list_of_favorite_books()

2023-12-14 18:33 UTC, kadirovgm commented on tests.py
> +        collector.favorites = ["Властелин Колец", "Институт", "Чайка"]
нужно исправить: для чего этот список? 

тест прост: 
- добавляешь книгу в словарь
- добавляешь ее в избранные
- удаляешь ее из избранных
- проверяешь, что этой книги в избранных нет

2023-12-18 13:25 UTC, KrylovaLena commented on tests.py
> +        collector.favorites.append(book_name)
Всё верно, что на метод add_book_in_favorites написан тест, этот тест был, что повторно не добавляется одна и та же книга. Удалила, если считаете излишним.

2023-12-18 13:32 UTC, KrylovaLena commented on tests.py
> +        collector.favorites = ["Властелин Колец", "Институт", "Чайка"]
если при написании тестов использовать методы добавления книги, добавления в избранное это не будет ошибкой? у нас может метод добавления книги в избранное работать некорректно, а метод удаления - работать корректно. Тест же упадёт. Но в данном тесте мы должны проверить работу именно удаления из избранного.

2023-12-18 13:44 UTC, KrylovaLena commented on tests.py
> +        book_name = "Сказка о Тройке. История непримиримой борьбы за повышение трудовой дисциплины, против бюрократизма, за высокий моральный уровень, против обезлички, за здоровую критику и здоровую
удалила этот тест, т.к. написала параметризированный тест, покрывающий этот кейс

2023-12-18 14:55 UTC, KrylovaLena commented
Актуальная версия в коммите 6ae77bad5c93b5178b210c33e5e50172e8acf844

2023-12-18 15:41 UTC, kadirovgm approved these changes

2023-12-18 15:41 UTC, kadirovgm commented on tests.py
> +    '''Проверка добавления двух новых книг в коллекцию.'''
отлично!

2023-12-25 10:02 UTC, merged